/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ne.sakura.uhideyuki.jatcoder;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
