#!/usr/bin/env ruby
# -*- mode: Ruby -*-
require 'erb'

CODE_PATH = "../code/src/main/java/jp/ne/sakura/uhideyuki/jatcoder"

clsname = ARGV[0].capitalize

if Dir.exist?(clsname)
  puts("Directory #{clsname} already exist.")
  exit(1)
end

Dir.mkdir(clsname)

template = <<'EOS'
package jp.ne.sakura.uhideyuki.jatcoder;
import java.util.*;
import java.io.PrintWriter;

public class <%= clsname %> {
  private final FastScanner sc;
  private final PrintWriter out;
  public <%= clsname %>(){
    sc = new FastScanner();
    out = new PrintWriter(System.out);
  }

  public void solve(){

    out.flush();
  }
}
EOS

erb = ERB.new(template)

File.open("#{CODE_PATH}/#{clsname}.java", "w") do |f|
  f.write(erb.result)
end

system("cd #{clsname}; ln -s ../#{CODE_PATH}/#{clsname}.java .")



         





