/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package jp.ne.sakura.uhideyuki.jatcoder;

import static org.junit.jupiter.api.Assertions.*;

import java.util.ArrayList;
import java.util.function.BiFunction;
import java.util.function.Function;
import org.junit.jupiter.api.Test;

class LazySegtreeTest {
    private final BiFunction<Integer, Integer, Integer> op = (a, b) -> { return a + b; };
    private final Integer e = 0;
    private final Integer f = 2;
    private final BiFunction<Integer, Integer, Integer> mapping =
            (f, x) -> { return f * x; };
    private final BiFunction<Integer, Integer, Integer> composition =
            (f, g) -> { return f * g; };
    private final Integer id = 1;
    @Test
    void lazySegtree_set_get() {
        final int n = 100;
        final LazySegtree<Integer, Integer> seg = new LazySegtree<>(op, e, mapping, composition, id, n);
        for (int i = 0; i < n; i++) {
            seg.set(i, i);
        }
        for (int i = 0; i < n; i++) {
            assertEquals(i, seg.get(i));
        }
    }

    @Test
    void lazySegtree__set_prod() {
        final int n = 100;
        final LazySegtree<Integer, Integer> seg = new LazySegtree<>(op, e, mapping, composition, id, n);
        final ArrayList<Integer> arr = new ArrayList<>(n);
        for (int i = 0; i < n; i++){
            arr.add(i);
            seg.set(i, i);
        }

        for (int l = 0; l < n; l++){
            for (int r = l; r <= n; r++){
                int sum = 0;
                for (int i = l; i < r; i++) {
                    sum += arr.get(i);
                }
                assertEquals(sum, seg.prod(l, r));
                if ((l == 0) && (r == n)) {
                    assertEquals(sum, seg.allProd());
                }
            }
        }
    }

    @Test
    void lazySegtree__list_prod() {
        final int n = 100;
        final ArrayList<Integer> arr = new ArrayList<>(n);
        for (int i = 0; i < n; i++){
            arr.add(i);
        }
        final LazySegtree<Integer, Integer> seg = new LazySegtree<>(op, e, mapping, composition, id, arr);

        for (int l = 0; l < n; l++){
            for (int r = l; r <= n; r++){
                int sum = 0;
                for (int i = l; i < r; i++) {
                    sum += arr.get(i);
                }
                assertEquals(sum, seg.prod(l, r));
                if ((l == 0) && (r == n)) {
                    assertEquals(sum, seg.allProd());
                }
            }
        }
    }

    @Test
    void lazySegtree_maxRight() {
        final int n = 100;
        final LazySegtree<Integer, Integer> seg = new LazySegtree<>(op, e, mapping, composition, id, n);
        for (int i = 0; i < n; i++) {
            seg.set(i, 1);
        }
        final int w = 19;
        final Function<Integer, Boolean> f = (s) -> { return s <= w; };
        for (int l = 0; l <= n; l++){
            final int r = seg.maxRight(l, f);
            if (l + w <= n) {
                assertEquals(w, r - l);
            } else {
                assertEquals(n, r);
            }
        }
    }

    @Test
    void lazySegtree_minLeft() {
        final int n = 100;
        final LazySegtree<Integer, Integer> seg = new LazySegtree<>(op, e, mapping, composition, id, n);
        for (int i = 0; i < n; i++) {
            seg.set(i, 1);
        }
        final int w = 19;
        final Function<Integer, Boolean> f = (s) -> { return s <= w; };
        for (int r = 0; r <= n; r++){
            final int l = seg.minLeft(r, f);
            if (r - w >= 0) {
                assertEquals(w, r - l);
            } else {
                assertEquals(0, l);
            }
        }
    }

    @Test
    void lazySegtree__set_prod2() {
        final int n = 100;
        final LazySegtree<Integer, Integer> seg = new LazySegtree<>(op, e, mapping, composition, id, n);
        final ArrayList<Integer> arr = new ArrayList<>(n);
        for (int i = 0; i < n; i++){
            arr.add(i*2);
            seg.set(i, i);
        }
        seg.apply(0, n, f);

        for (int l = 0; l < n; l++){
            for (int r = l; r <= n; r++){
                int sum = 0;
                for (int i = l; i < r; i++) {
                    sum += arr.get(i);
                }
                assertEquals(sum, seg.prod(l, r));
                if ((l == 0) && (r == n)) {
                    assertEquals(sum, seg.allProd());
                }
            }
        }
    }

    @Test
    void lazySegtree_maxRight2() {
        final int n = 100;
        final LazySegtree<Integer, Integer> seg = new LazySegtree<>(op, e, mapping, composition, id, n);
        for (int i = 0; i < n; i++) {
            seg.set(i, 1);
        }
        for (int i = 0; i < n; i+=10){
            seg.apply(i, Math.min(i + 10, n), f);
        }

        final int w = 19;
        final Function<Integer, Boolean> g = (s) -> { return s <= 2 * w; };
        for (int l = 0; l <= n; l++){
            final int r = seg.maxRight(l, g);
            if (l + w <= n) {
                assertEquals(w, r - l);
            } else {
                assertEquals(n, r);
            }
        }
    }

    @Test
    void lazySegtree_minLeft2() {
        final int n = 100;
        final LazySegtree<Integer, Integer> seg = new LazySegtree<>(op, e, mapping, composition, id, n);
        for (int i = 0; i < n; i++) {
            seg.set(i, 1);
        }
        for (int i = 0; i < n; i+=15){
            seg.apply(i, Math.min(i + 15, n), f);
        }
        for (int i = 0; i < n; i+=20){
            seg.apply(i, Math.min(i + 20, n), f);
        }

        final int w = 19;
        final Function<Integer, Boolean> g = (s) -> { return s <= 4 * w; };
        for (int r = 0; r <= n; r++){
            final int l = seg.minLeft(r, g);
            if (r - w >= 0) {
                assertEquals(w, r - l);
            } else {
                assertEquals(0, l);
            }
        }
    }
}
